workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build

version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: dockdockem
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: dockdockem
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw test
